name: Linters

on:
    push:
        branches: [ "main", "new/redesign" ]
    pull_request:
        branches: [ "main", "new/redesign" ]

jobs:
    build:
        runs-on: ubuntu-22.04

        name: Run linters

        steps:

        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
              node-version: 20
              cache: 'npm'

        - name: Install dependencies
          run: make install

        - name: Run the linters
          run: make lint
